version: '3.5'

services:
  db:
    container_name: thomisis-db
    image: devopseasylearning/apha-db:latest
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      # MYSQL_USER: admin
      # MYSQL_PASSWORD: GzWNQY8eH4YBkt8HutZj@*J
      # MYSQL_DATABASE: weatherapp
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - thomisis
    restart: always

  redis:
    container_name: thomisis-redis
    image: devopseasylearning/apha-redis:latest
    networks:
      - thomisis
    environment:
      REDIS_USER: redis
      REDIS_PASSWORD: redis
    volumes:
      - redis-data:/data
    restart: always

  weather:
    container_name: thomisis-weather
    image: devopseasylearning/apha-weather:v1.0.0
    expose:
      - 5000
    environment:
      APIKEY: ecbc396f46mshb65cbb1f82cf334p1fcc87jsna5e962a3c542
    networks:
      - thomisis
    restart: always
    depends_on:
      - db
      - redis # Weather depends on both db and redis

  auth:
    container_name: thomisis-auth
    image: devopseasylearning/apha-auth:v1.0.0
    environment:
      DB_HOST: db
      DB_PASSWORD: my-secret-pw
    expose:
      - 8080
    networks:
      - thomisis
    restart: always
    depends_on:
      - weather # Auth depends on the weather service

  ui:
    container_name: thomisis-ui
    image: devopseasylearning/apha-ui:v1.0.0
    environment:
      AUTH_HOST: auth
      AUTH_PORT: 8080
      WEATHER_HOST: weather
      WEATHER_PORT: 5000
      REDIS_USER: redis
      REDIS_PASSWORD: redis
    expose:
      - 3000
    ports:
      - 3000:3000
    networks:
      - thomisis
    restart: always
    depends_on:
      - auth # UI depends on Auth

networks:
  thomisis:
    driver: bridge

volumes:
  db-data:
  redis-data:
